---
title: "Rinbix Predict RNA-Seq Pipeline"
author: "Bill White"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Rinbix Predict RNA-Seq Pipeline}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

#Load Rinbix and SImulated Data Set

```{r}
library(Rinbix)
data(simrnaseq)
```

#Pipeline Call

```{r}
set.seed(1965)
predictResult <- predictRnaseq(rnaseqCountsTrain=predictorsTrain, 
                               groupLabelsTrain=responseTrain, 
                               rnaseqCountsTest=predictorsTest, 
                               groupLabelsTest=responseTest, 
                               preprocessMethod="none", 
                               filterMethod="randomforests", 
                               topN=10, 
                               classifierMethod="svm",
                               verbose=FALSE)
predictResult
```

#Implemented as Separate Function Calls

```{r}
set.seed(1965)
preprocessResult <- preprocessRnaseq(method="log2", 
                                     predictorsTrain, 
                                     predictorsTest, 
                                     verbose=FALSE)
cat("Before preprocessing:\n")
predictorsTrain[1:5, 1:5]
cat("After preprocessing:\n")
preprocessResult$train[1:5, 1:5]

filterResult <- filterRnaseq(method="randomforests", 
                             preprocessResult$train, 
                             responseTrain, 
                             preprocessResult$test, 
                             responseTest,
                             nTopGenes=10, 
                             verbose=FALSE)

cat("Genes before filtering:", ncol(preprocessResult$train), 
    "after:", ncol(filterResult$train), "\n")

classifyStats <- classifyRnaseq(method="svm", 
                                filterResult$train, 
                                responseTrain, 
                                filterResult$test, 
                                responseTest,
                                verbose=FALSE)
classifyStats
```
